# Generated by Django 5.0.14 on 2026-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='optional_questions_asked',
            field=models.BooleanField(default=False),
        ),
    ]
